# Generated by Django 5.2 on 2025-04-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
