# Generated by Django 5.2 on 2025-04-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_items', '0003_lostitem_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
