# Generated by Django 5.2 on 2025-04-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('clothing', 'Clothing'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('found_date', models.DateField()),
                ('found_location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='found_items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
